/**
 * Regenerates src/image-aspects.js from the images actually on disk.
 *
 * The aspect ratios reserve the banknote's space before the image has been
 * downloaded: without them the card would collapse and re-expand on every
 * challenge. They have to be the real ones, per file, because four of the ten
 * designs are portrait and the six denominations differ from each other.
 *
 * Reads the PNG/WebP header directly rather than pulling in an image library:
 * the site has no runtime dependencies and the tooling should not need any
 * either. Run it after adding or re-orienting any banknote image.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = resolve(ROOT, 'assets/banknotes');
const OUT = resolve(ROOT, 'src/image-aspects.js');

/**
 * Width and height of a WebP file. Handles the three chunk layouts — lossy
 * (VP8), lossless (VP8L) and extended (VP8X) — because the encoder picks
 * whichever is smaller and we do not get to choose.
 */
function webpSize(buf) {
  if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') {
    throw new Error('non è un file WebP');
  }
  const chunk = buf.toString('ascii', 12, 16);

  if (chunk === 'VP8X') {
    return {
      width: 1 + buf.readUIntLE(24, 3),
      height: 1 + buf.readUIntLE(27, 3),
    };
  }
  if (chunk === 'VP8 ') {
    return { width: buf.readUInt16LE(26) & 0x3fff, height: buf.readUInt16LE(28) & 0x3fff };
  }
  if (chunk === 'VP8L') {
    const b = buf.readUInt32LE(21);
    return { width: (b & 0x3fff) + 1, height: ((b >> 14) & 0x3fff) + 1 };
  }
  throw new Error(`chunk WebP sconosciuto: ${chunk}`);
}

const files = readdirSync(DIR).filter((f) => f.endsWith('.webp')).sort();
const aspects = {};
let portrait = new Set();

for (const file of files) {
  const key = file.replace(/^banknote-design-proposal-/, '').replace(/\.webp$/, '');
  const { width, height } = webpSize(readFileSync(resolve(DIR, file)));
  aspects[key] = Number((width / height).toFixed(4));
  if (width < height) portrait.add(key.split('-')[0]);
}

const verticali = [...portrait].sort().map((d) => d.toUpperCase());
const body = Object.entries(aspects)
  .map(([k, v]) => `  '${k}': ${v},`)
  .join('\n');

writeFileSync(
  OUT,
  `/**
 * Aspect ratio (width / height) of every image.
 *
 * GENERATED BY tools/measure-images.mjs — DO NOT EDIT BY HAND.
 *
 * These reserve the banknote's space before the image is downloaded: without
 * them the card would collapse and re-expand on every challenge. They are the
 * real ratios, not an average — ${verticali.length} of the ten designs
 * (${verticali.join(', ')}) are drawn portrait.
 */

export const IMAGE_ASPECTS = {
${body}
};

/** Aspect ratio of one image; 1.94 is the average of the landscape banknotes. */
export function imageAspect(designId, denomination, side) {
  return IMAGE_ASPECTS[\`\${designId}-\${denomination}-\${side}\`] ?? 1.94;
}

/**
 * True for the designs drawn portrait. The ECB publishes their files rotated
 * 90°; the images in this repository have already been turned upright, so the
 * ratio is enough to tell.
 */
export function isPortrait(designId) {
  return imageAspect(designId, 50, 'front') < 1;
}
`
);

console.log(`${files.length} immagini misurate`);
console.log(`disegni verticali: ${verticali.join(', ')}`);
